In [2]:
import numpy as np

## numpy arrays

In [3]:
benimListem =[20,90,890]

In [4]:
np.array(benimListem)

array([ 20,  90, 890])

In [8]:
matrixLitesi= [[10,20],[40,60],[60,90]]

In [9]:
np.array(matrixLitesi)

array([[10, 20],
       [40, 60],
       [60, 90]])

## arange

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,4)

array([0, 4, 8])

## linspace

In [20]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.randn(5)

array([ 0.4395506 , -0.47570941, -0.81410769, -0.14894338,  1.1003174 ])

In [26]:
benimDizim=np.arange(0,10)

In [27]:
benimDizim[3:6]=-2

In [28]:
benimDizim

array([ 0,  1,  2, -2, -2, -2,  6,  7,  8,  9])

In [32]:
baskaDizi=benimDizim[6:9]

In [34]:
baskaDizi[:]=100

In [35]:
baskaDizi

array([100, 100, 100])

In [36]:
benimDizim

array([  1,   1,   1,   1,   1,   1, 100, 100, 100,   1])

## matrix

In [37]:
benimListem = [[10,20,30],[1,5,6],[1,9,30]]

In [38]:
benimMatrixListem = np.array(benimListem)

In [42]:
benimMatrixListem[[2,0,1]]

array([[ 1,  9, 30],
       [10, 20, 30],
       [ 1,  5,  6]])

## operations

In [50]:
yeniBirDizi = np.random.randint(5,40,20)

In [51]:
yeniBirDizi

array([34, 39,  6, 32, 36,  8, 28, 21, 31, 18,  9, 26, 20, 12, 13,  6, 10,
       15, 35, 38])

In [52]:
yeniBirDizi >24

array([ True,  True, False,  True,  True, False,  True, False,  True,
       False, False,  True, False, False, False, False, False, False,
        True,  True])

In [53]:
sonucDizisi=yeniBirDizi>24

In [54]:
sonucDizisi

array([ True,  True, False,  True,  True, False,  True, False,  True,
       False, False,  True, False, False, False, False, False, False,
        True,  True])

In [56]:
yeniBirDizi[sonucDizisi]

array([34, 39, 32, 36, 28, 31, 26, 35, 38])